jlsite/jlsite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/', views.logout, name='logout', kwargs={'next_page': '/'}),
]

jlsite/quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.QuizView.as_view(), name='index'),
    path('register/', views.UserFromView.as_view(), name='register'),
    path('<int:pk>', views.QuizQuestionsView.as_view(), name='quiz-take'),
    
    path('quiz/yourresult/<int:pk>', views.show_taken_quiz, name='taken-quiz'),
    
    # /quiz/add
    path('quiz/create', views.create_quiz, name='quiz-create'),
    path('quiz/save', views.save_quiz, name='save'),
    path('quiz/results', views.UserResultsView.as_view()),
    path('quiz/allresults', views.all_user_results),

]

jlsite/quiz/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser


class Quiz(models.Model):
    quiz_name = models.CharField(max_length=100)
    pub_date = models.DateTimeField(auto_now=True)
    
    def get_absolute_url(self):
        return reverse('quiz:quiz-take', kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.quiz_name


class Question(models.Model):
    TYPES = (
        ('radio', 'radio'),
        ('checkbox', 'checkbox'),
        ('text', 'text'),
    )
    
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200, default=' ')
    pub_date = models.DateTimeField(auto_now=True)
    question_type = models.CharField(max_length=10, choices=TYPES, default='radio')
    correct_answer = models.TextField(default='')
    
    def __str__(self):
        return self.question_text
    
    def correct_ans_as_list(self):
        return self.correct_answer.split(',')


class UserResults(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    answers = models.TextField(default='')
    submission_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return "%s's profile" % self.user


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField(default='')
    explanation = models.TextField(default='yep')
    
    def __str__(self):
        return self.choice_text

jlsite/quiz/forms.py
from django import forms
from .models import Quiz, Question, Answer
from django.contrib.auth.models import User
from django.forms import inlineformset_factory


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['choice_text']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

jlsite/quiz/views.py
import json
from urllib.parse import parse_qs

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import View

from .forms import UserForm
from .models import Question, Quiz, UserResults, Answer


# Create your views here.
# @login_required
class QuizView(LoginRequiredMixin, generic.ListView):
    template_name = 'quiz/index.html'
    context_object_name = 'quiz_list'
    
    def get_queryset(self):
        return Quiz.objects.all()


class QuizQuestionsView(LoginRequiredMixin, generic.DetailView):
    model = Quiz
    template_name = 'quiz/quiz_take.html'


class UserFromView(View):
    form_class = UserForm
    template_name = 'registration/reg_form.html'
    
    # blank form for new user
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})
    
    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            
            # normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            
            #
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('quiz:index')
        return render(request, self.template_name, {'form': form})


class UserResultsView(LoginRequiredMixin, View):
    
    def get(self, request):
        template_name = 'quiz/user_results.html'
        user = request.user
        
        context = {
            'user_results': UserResults.objects.filter(user__id=user.id),
        }
        return render(request, template_name, context)
    
    def post(self, request):
        answers = request.POST['answers']
        user_id = request.POST['user_id']
        quiz_id = request.POST['quiz_id']
        
        quiz = Quiz.objects.get(pk=quiz_id)
        questions = quiz.question_set.all()
        user_score = 0
        answers_dict = parse_qs(answers)
        for question in questions:
            if 'question{}'.format(question.id) in answers_dict:
                if ','.join(answers_dict['question{}'.format(question.id)]) == question.correct_answer:
                    user_score += 1
        
        new_result = UserResults.objects.create(
            quiz=quiz,
            score=user_score,
            user=User.objects.get(pk=user_id),
            answers=answers
        )
        return HttpResponse(new_result.id)


@login_required()
def all_user_results(request):
    template_name = 'quiz/all_user_results.html'
    context = {
        'user_results': UserResults.objects.all(),
    }
    return render(request, template_name, context)


def show_taken_quiz(request, pk=None):
    template_name = 'quiz/show_result.html'
    user_result = UserResults.objects.filter(pk=pk)[0]
    answers_dict = parse_qs(user_result.answers)
    context = {
        'answers_dict': answers_dict,
        'user_result': user_result,
    }
    
    return render(request, template_name, context)


@login_required()
def create_quiz(request):
    template_name = 'quiz/quiz_create.html'
    return render(request, template_name)


@login_required()
def save_quiz(request):
    if request.method == 'POST':
        quiz_name = request.POST['quiz_name']
        quiz_data = request.POST['quiz_data']
        
        quiz_data = json.loads(quiz_data)
        quiz = Quiz.objects.create(quiz_name=quiz_name)
        
        print(quiz_data)
        for key, value in quiz_data.items():
            print(value['type'])
            question = Question.objects.create(quiz=quiz, question_text=key, question_type=value['type'],
                                               correct_answer=','.join(value['correctAnswers']))
            for i in value['answers']:
                Answer.objects.create(question=question, choice_text=i)
    return HttpResponse('')


def logout_view(request):
    logout(request)
    return redirect('quiz:index')

jlsite/quiz/templates/quiz/all_user_results.html
{% extends 'quiz/base.html' %}
{% block content %}
{% if user.is_superuser %}

<h1>All user results:</h1>
<table class="table">
    <thead>
    <tr>
        <th scope="col">username</thscope>
        <th scope="col">quiz name</th>
        <th scope="col">result</th>
        <th scope="col">date</th>
    </tr>
    </thead>
    <tbody>
    {%for user_result in user_results%}
    <tr>
        <th scope="row">{{user_result.user.username}}</th>
        <th scope="row">{{user_result.quiz.quiz_name}}</th>
        <td><a href="/quiz/yourresult/{{user_result.id}}">{{user_result.score}}</a></td>
        <td>{{user_result.submission_date}}</td>
    </tr>
    {%endfor%}

    </tbody>
</table>
{% else %}
<h3>permission denied</h3>
{% endif %}
{% endblock content %}

jlsite/quiz/templates/quiz/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Material Design for Bootstrap fonts and icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">

    <!-- Material Design for Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css"
          integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


    <title>QUIZ APP</title>
</head>

<body>
<header>
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Quizzer</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{user.username}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/quiz/results">My Results</a>
                        {% if user.is_superuser %}
                        <a class="dropdown-item" href="/quiz/allresults">All Results</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/accounts/logout/">Logout</a>
                    </div>
                </li>

            </ul>
        </div>
    </nav>

    {%else%}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Quizzer</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="hhhhhnavbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/login/">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/register">Sign up!</a>
                </li>

            </ul>
        </div>
    </nav>
    {%endif%}
</header>
{% block content %}
{% endblock %}

<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js"
        integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
        integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9"
        crossorigin="anonymous"></script>
<script>$(document).ready(function () {
    $('body').bootstrapMaterialDesign();
});</script>
</body>
</html>

jlsite/quiz/templates/quiz/index.html
{% extends 'quiz/base.html' %}

{% block content %}
<div class="container-fluid">
    <h2>quiz list:</h2>

    <div class="list-group">
        {% for quiz in quiz_list %}
        <a href="{% url 'quiz:quiz-take' quiz.id %}" class="list-group-item">{{ quiz.quiz_name }}</a>
        {% endfor %}

    </div>
    {% if user.is_superuser %}
    <a href="{% url 'quiz:quiz-create' %}" class="btn btn-info" role="button">create quiz</a>
    {% endif %}
    {% endblock content %}
</div>

jlsite/quiz/templates/quiz/quiz_create.html
{% extends 'quiz/base.html' %}
{% block content %}
{% if user.is_superuser %}
{% load static %}

<style>
    .answer input {
        vertical-align: middle;
    }

</style>
<div class="container-fluid">
    <div>
        <div id="quizContainer" class="container-fluid">

            <h2>Create Quiz with name <input id="quizName" type="text" class="form-control" aria-label="Default"
                                             aria-describedby="inputGroup-sizing-default">
            </h2>
            <span class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Add Question</button>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="#" onclick="addQuestion('checkbox')">Add Checkbox Question</a></li>
      <li><a class="dropdown-item" href="#" onclick="addQuestion('radio')">Add Radiobutton Question</a></li>
      <li><a class="dropdown-item" href="#" onclick="addQuestion('text')">Add Free Question</a></li>
    </ul>
</span>
        </div>
        <button class="btn btn-success btn-block" onclick="sendRequest()"> FINISH</button>
    </div>
</div>

<!--hoidden template for adding radio button and checkbox questions-->
<script id="hidden-template-QSTN-RB-CB" type="text/x-custom-template">
    <div id="{0}" class="question" type="{1}">
        <hr>
        <span class="input-group ">
        <span class="input-group-prepend">
            <span class="input-group-text" id="basic-addon3">question text:</span>
        </span>
        <input type="text" class="question form-control" id="basic-url" aria-describedby="basic-addon3">
        <button type="button" class="btn deleteBtn" onclick="deleteThing(this)"><code>DEL</code></button>  </span>
        <button class="btn btn-primary" id="answerAdd" onclick="addAnswer('{0}','{1}')">add answer</button>
    </div>
</script>
<!--hidden template for adding text questions-->
<script id="hidden-template-QSTN-TXT" type="text/x-custom-template">
    <div id="{0}" type="{1}" class=\"question\">
        <hr>
        <span class="form-group">
        <label for="exampleTextarea" class="bmd-label-floating">input your open question</label>
        <textarea type="open" class="form-control question" id="exampleTextarea" rows="3"></textarea>
    </span>
        <br>
        <span class="input-group mb-3">
           <span class="input-group-prepend">
               <span class="input-group-text" id="basic-addon3">answer text:</span>
           </span>
           <input type="text" class="answerText form-control" id="basic-url" aria-describedby="basic-addon3">
       </span>
    </div>
    <hr>
</script>

<script id="hidden-template-ANSW" type="text/x-custom-template">
    <div class="input-group mb-3">
        <span class="input-group-prepend">
            <span class="input-group-text" id="basic-addon3">correct?</span>
            <span class="input-group-text" id="basic-addon3"><input id="{1}" class="answer" type="{0}"
                                                                    name="{1}"></span>
            <span class="form-group">
                <label for="lol" class="bmd-label-floating">choice text</label>
                <input type="text" class="answerText form-control" id="lol" aria-describedby="basic-addon3">
            </span>
                <button type="button" class="btn deleteBtn" onclick="deleteThing(this)"><code>DEL</code></button>
        </span>
    </div>
</script>


<script type="text/javascript" src="{% static 'quiz/quiz_create.js' %}"></script>
{% else %}
<p>PEMISSiON DENIED</p>
{% endif %}

{% endblock content %}

jlsite/quiz/templates/quiz/quiz_take.html
{% extends 'quiz/base.html' %}
{% block content %}
{% load static %}
<div class="row justify-content-center">
    <div class="form-group col-sm-6">
        <h1>{{ quiz.quiz_name }}</h1>
        <hr>

        <form id="sendquiz" action="" enctype="multipart/form-data">
            {% csrf_token %}

            {% for question in quiz.question_set.all%}
            <div class="panel-body" id={{question.id}}> {{question.question_text}} :</div>
            <div class="form-group col-sm-6">
                {% for answer in question.answer_set.all %}
                {% if question.question_type != 'text'%}

                <div class="{{question.question_type}}">
                    <label>
                        <input type="{{question.question_type}}" name="question{{question.id}}"
                               value="{{answer.choice_text}}">
                        {{answer.choice_text}}
                    </label>
                </div>
                {%else%}
                <div class="form-group">
                    <input type="text" class="form-control" name="question{{question.id}}">
                    <span class="bmd-help">input answer here.</span>
                </div>
                {% endif%}

                {%endfor%}
            </div>
            {%endfor%}
            <button type="submit" class="btn btn-outline-success">SUBMIT</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    var quiz_id = '{{quiz.id}}';
    var user_id = '{{user.id}}';
</script>
<script type="text/javascript" src="{% static 'quiz/quiz_take.js' %}"></script>
{% endblock content %}

jlsite/quiz/templates/quiz/show_result.html
{% extends 'quiz/base.html' %}
{% load utils %}

{% block content %}
{% for question in user_result.quiz.question_set.all %}
{% with answers_dict|get_value_from_dict:question.id as usr_ans %}

<div>question{{question.id}}:</div>
<div>{{question.question_text }}</div>
<div>your answer {{usr_ans}}</div>
<div>correct answer is {{question.correct_ans_as_list}}</div>

{% with usr_ans|compare_lists:question.correct_ans_as_list as is_corr %}

{% if is_corr %}
<p>AWESOME</p>
{% else %}
<p>WRONG</p>
{% endif %}

{% endwith %}
{% endwith %}

{% endfor %}
<h2>YOUR SCORE IS {{user_result.score}}</h2>
{% endblock content %}

jlsite/quiz/templates/quiz/user_results.html
{% extends 'quiz/base.html' %}
{% block content %}
<h1>Your results, {{user.username}}!</h1>

<table class="table">
    <thead>
    <tr>
        <th scope="col">quiz name</th>
        <th scope="col">result</th>
        <th scope="col">date</th>
    </tr>
    </thead>
    <tbody>
    {%for user_result in user_results%}
    <tr>
        <th scope="row">{{user_result.quiz.quiz_name}}</th>
        <td><a href="/quiz/yourresult/{{user_result.id}}">{{user_result.score}}</a></td>
        <td>{{user_result.submission_date}}</td>
    </tr>
    {%endfor%}

    </tbody>
</table>
{% endblock content %}